name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.11.0

  cupertino_icons: ^1.0.2
#  google_fonts: ^3.0.1
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/map.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/
    - assets/images/
